# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weatherApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weatherApp
  pod 'Alamofire',
      :git => 'https://github.com/Alamofire/Alamofire.git',
      :branch => 'master'

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React',
      :path => '../node_modules/react-native',
      :subspecs => [
        'Core',
        'CxxBridge', # Include this for RN >= 0.47
        'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket', # needed for debugging
        'RCTAnimation',
        'RCTActionSheet',
        'RCTImage'
      ]
      # Explicitly include Yoga if you are using RN >= 0.42.0

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
end
